#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: U-Boot-CI

on:
  push:
    branches: 
      - master

  release:
    types: [published]

jobs:
  build_openwrt:
    name: Build U-Boot
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Build Depends
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential gcc-mipsel-linux-gnu python3-setuptools

      - name: Compile firmware
        run: |
          bash ./helper/build.sh

      - name: Deliver firmware
        uses: actions/upload-artifact@v2
        with:
          name: U-Boot-firmware
          path: ./build-output/

      - name: Upload release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build-output/*
          tag: ${{ github.ref }}-autorelease
          file_glob: true
